"""increase password_hash length

Revision ID: 159e5250694b
Revises: 8b9d694f17a8
Create Date: 2025-09-19 13:55:52.895354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159e5250694b'
down_revision = '8b9d694f17a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
